// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Answer struct {
	ID          string `json:"id"`
	IsTrue      bool   `json:"isTrue"`
	QuestionID  string `json:"questionID"`
	AnswerField string `json:"answerField"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type AnswerInput struct {
	IsTrue      bool   `json:"isTrue"`
	AnswerField string `json:"answerField"`
}

type Collection struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type FullCollection struct {
	Collection *Collection     `json:"collection"`
	Questions  []*FullQuestion `json:"questions,omitempty"`
}

type FullQuestion struct {
	ID            string    `json:"id"`
	QuestionField string    `json:"questionField"`
	CreatedAt     string    `json:"createdAt"`
	Answers       []*Answer `json:"answers,omitempty"`
}

type Group struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	TeacherName string `json:"teacherName"`
	Level       string `json:"level"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}

type Question struct {
	ID            string `json:"id"`
	QuestionField string `json:"questionField"`
	CollectionID  string `json:"collectionID"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type Response struct {
	StatusCode int    `json:"statusCode"`
	Message    string `json:"message"`
}

type Student struct {
	ID          string `json:"id"`
	PhoneNumber string `json:"phoneNumber"`
	FullName    string `json:"fullName"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type TestQuestion struct {
	QuestionField string         `json:"questionField"`
	Answers       []*AnswerInput `json:"answers"`
}

type GroupLevel string

const (
	GroupLevelBeginner          GroupLevel = "BEGINNER"
	GroupLevelElementary        GroupLevel = "ELEMENTARY"
	GroupLevelPreIntermediate   GroupLevel = "PRE_INTERMEDIATE"
	GroupLevelIntermediate      GroupLevel = "INTERMEDIATE"
	GroupLevelUpperIntermediate GroupLevel = "UPPER_INTERMEDIATE"
	GroupLevelAdvanced          GroupLevel = "ADVANCED"
	GroupLevelProficient        GroupLevel = "PROFICIENT"
)

var AllGroupLevel = []GroupLevel{
	GroupLevelBeginner,
	GroupLevelElementary,
	GroupLevelPreIntermediate,
	GroupLevelIntermediate,
	GroupLevelUpperIntermediate,
	GroupLevelAdvanced,
	GroupLevelProficient,
}

func (e GroupLevel) IsValid() bool {
	switch e {
	case GroupLevelBeginner, GroupLevelElementary, GroupLevelPreIntermediate, GroupLevelIntermediate, GroupLevelUpperIntermediate, GroupLevelAdvanced, GroupLevelProficient:
		return true
	}
	return false
}

func (e GroupLevel) String() string {
	return string(e)
}

func (e *GroupLevel) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GroupLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GroupLevel", str)
	}
	return nil
}

func (e GroupLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
